before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^example:'

dockers:
  - image_templates:
      - "ghcr.io/zekker6/external-dns-provider-adguard:latest"
      - "ghcr.io/zekker6/external-dns-provider-adguard:{{ .Tag }}"
